# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Authentication.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x41uthentication.proto\x12\x05Proto\"D\n\x0fRegisterRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"#\n\x10RegisterResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\"2\n\x1f\x41\x63\x63\x65ssProtectedResourceResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xf8\x01\n\x0b\x41uthService\x12;\n\x08Register\x12\x16.Proto.RegisterRequest\x1a\x17.Proto.RegisterResponse\x12\x32\n\x05Login\x12\x13.Proto.LoginRequest\x1a\x14.Proto.LoginResponse\x12O\n\x17\x41\x63\x63\x65ssProtectedResource\x12\x0c.Proto.Empty\x1a&.Proto.AccessProtectedResourceResponse\x12\'\n\tCleanupDb\x12\x0c.Proto.Empty\x1a\x0c.Proto.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Authentication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=31
  _globals['_REGISTERREQUEST']._serialized_end=99
  _globals['_REGISTERRESPONSE']._serialized_start=101
  _globals['_REGISTERRESPONSE']._serialized_end=136
  _globals['_LOGINREQUEST']._serialized_start=138
  _globals['_LOGINREQUEST']._serialized_end=185
  _globals['_LOGINRESPONSE']._serialized_start=187
  _globals['_LOGINRESPONSE']._serialized_end=217
  _globals['_ACCESSPROTECTEDRESOURCERESPONSE']._serialized_start=219
  _globals['_ACCESSPROTECTEDRESOURCERESPONSE']._serialized_end=269
  _globals['_EMPTY']._serialized_start=271
  _globals['_EMPTY']._serialized_end=278
  _globals['_AUTHSERVICE']._serialized_start=281
  _globals['_AUTHSERVICE']._serialized_end=529
# @@protoc_insertion_point(module_scope)
